# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jaDqaM2YI97JyFJv9omKzFIh8k9FOJLg
"""

import pickle
import numpy as np
import pandas as pd

model = pickle.load(open('model.pkl', 'rb'))
class_names = ['0', '1']

def predict(dataset): 
   
    dataset = dataset[["radius_mean",	"texture_mean",	"perimeter_mean",	"area_mean",	"smoothness_mean",	"compactness_mean",	"concavity_mean",	"concave points_mean",	"symmetry_mean",	"fractal_dimension_mean",
   	"radius_se",	"texture_se",	"perimeter_se",	"area_se",	"smoothness_se",	"compactness_se",	"concavity_se",	"concave points_se",	"symmetry_se",	"fractal_dimension_se", "radius_worst",	"texture_worst",	"perimeter_worst",
    "area_worst",	"smoothness_worst",	"compactness_worst",	"concavity_worst",	"concave points_worst",	"symmetry_worst",	"fractal_dimension_worst"]]

    numpy_array = dataset.to_numpy()
  
    predictions = model.predict(numpy_array)

    output= [class_names[class_predicted] for class_predicted in predictions]
    if output == 0:
         return ('THE PATIENT IS MORE LIKELY TO HAVE A BENIGN CANCER.')
    else:
         return ('THE PATIENT IS MORE LIKELY TO HAVE A MALIGNANT CANCER. ')